# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mini_sehatq_development

test:
  <<: *default
  database: mini_sehatq_test

production:
  <<: *default
  host: ec2-50-17-90-177.compute-1.amazonaws.com
  database: mini_sehatq_production
  user: yovrqgxsosivcx
  password: bd6e60d9e8f2d244d967dc320b89566e4c9012d17d63b7213f5951aaf09f7bad
  port: 5432
